/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-23 04:07:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>ASHH Clothing</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"icon\" href=\"favicon.png\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("      body {\r\n");
      out.write("        font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        background-color: #f0f2f5;\r\n");
      out.write("        color: #333;\r\n");
      out.write("      }\r\n");
      out.write("      .ashh-title span {\r\n");
      out.write("        color: #2e7d32;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- Sticky Header & Navbar -->\r\n");
      out.write("    <div class=\"sticky-top bg-white\">\r\n");
      out.write("      <header class=\"text-center bg-white pt-4 pb-3 border-bottom\">\r\n");
      out.write("        <h1 class=\"ashh-title\">ASHH <span>Clothing</span></h1>\r\n");
      out.write("        <p class=\"ashh-subtitle\">Your Everyday Fashion Destination</p>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"navbar navbar-expand-lg bg-white py-3 shadow-sm\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <!-- Logo (small screens) -->\r\n");
      out.write("          <a class=\"navbar-brand d-lg-none\" href=\"#\">ASHH</a>\r\n");
      out.write("\r\n");
      out.write("          <!-- Hamburger -->\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"navbar-toggler\"\r\n");
      out.write("            type=\"button\"\r\n");
      out.write("            data-bs-toggle=\"collapse\"\r\n");
      out.write("            data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("            aria-label=\"Toggle navigation\"\r\n");
      out.write("          >\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <!-- Search (left) -->\r\n");
      out.write("            <div class=\"d-flex flex-grow-1\" style=\"flex-basis: 0\">\r\n");
      out.write("              <form class=\"d-flex w-100 mt-3 mb-2 mt-lg-0 mb-lg-0 nav-left\">\r\n");
      out.write("                <div class=\"input-group search-container\">\r\n");
      out.write("                  <input\r\n");
      out.write("                    class=\"form-control text-muted border-0 bg-light\"\r\n");
      out.write("                    type=\"search\"\r\n");
      out.write("                    placeholder=\"Search\"\r\n");
      out.write("                    aria-label=\"Search\"\r\n");
      out.write("                    style=\"border-radius: 20px 0 0 20px\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <button\r\n");
      out.write("                    class=\"btn text-white\"\r\n");
      out.write("                    type=\"submit\"\r\n");
      out.write("                    style=\"\r\n");
      out.write("                      background-color: #6b7091;\r\n");
      out.write("                      border-radius: 0 20px 20px 0;\r\n");
      out.write("                    \"\r\n");
      out.write("                  >\r\n");
      out.write("                    <svg\r\n");
      out.write("                      xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                      width=\"18\"\r\n");
      out.write("                      height=\"18\"\r\n");
      out.write("                      fill=\"currentColor\"\r\n");
      out.write("                      class=\"bi bi-search\"\r\n");
      out.write("                      viewBox=\"0 0 16 16\"\r\n");
      out.write("                    >\r\n");
      out.write("                      <path\r\n");
      out.write("                        d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </svg>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Center links -->\r\n");
      out.write("            <ul\r\n");
      out.write("              class=\"navbar-nav mx-auto mb-2 mb-xl-0 nav-center gap-3 justify-content-center\"\r\n");
      out.write("            >\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a\r\n");
      out.write("                  class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                  href=\"#\"\r\n");
      out.write("                  role=\"button\"\r\n");
      out.write("                  data-bs-toggle=\"dropdown\"\r\n");
      out.write("                  aria-expanded=\"false\"\r\n");
      out.write("                  >Bottoms</a\r\n");
      out.write("                >\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"jeans.html\">Jeans</a></li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"skirts.html\">Skirts</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a\r\n");
      out.write("                  class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                  href=\"#\"\r\n");
      out.write("                  role=\"button\"\r\n");
      out.write("                  data-bs-toggle=\"dropdown\"\r\n");
      out.write("                  aria-expanded=\"false\"\r\n");
      out.write("                  >Tops</a\r\n");
      out.write("                >\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"tshirts.html\">T-Shirts</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"shirts.html\">Shirts</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a\r\n");
      out.write("                  class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                  href=\"#\"\r\n");
      out.write("                  role=\"button\"\r\n");
      out.write("                  data-bs-toggle=\"dropdown\"\r\n");
      out.write("                  aria-expanded=\"false\"\r\n");
      out.write("                  >Casual</a\r\n");
      out.write("                >\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"dailywear.html\"\r\n");
      out.write("                      >Daily Wear</a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"streetstyle.html\"\r\n");
      out.write("                      >Street Style</a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a\r\n");
      out.write("                  class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                  href=\"#\"\r\n");
      out.write("                  role=\"button\"\r\n");
      out.write("                  data-bs-toggle=\"dropdown\"\r\n");
      out.write("                  aria-expanded=\"false\"\r\n");
      out.write("                  >Party</a\r\n");
      out.write("                >\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"dresses.html\">Dresses</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"gowns.html\">Gowns</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right: Register/Login & Cart -->\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"nav-right d-flex gap-3 align-items-center justify-content-center justify-content-lg-end mt-2 mt-lg-0 flex-grow-1\"\r\n");
      out.write("              style=\"flex-basis: 0\"\r\n");
      out.write("            >\r\n");
      out.write("              <a\r\n");
      out.write("                href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/register\"\r\n");
      out.write("                class=\"btn btn-outline-primary\"\r\n");
      out.write("              >\r\n");
      out.write("                <i class=\"fa-solid fa-user me-1\"></i> Register / Login\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-primary position-relative\">\r\n");
      out.write("                <i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("                <span\r\n");
      out.write("                  class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\"\r\n");
      out.write("                  style=\"font-size: 0.6em\"\r\n");
      out.write("                  >0\r\n");
      out.write("                  <span class=\"visually-hidden\">unread messages</span>\r\n");
      out.write("                </span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Video Section -->\r\n");
      out.write("    <section id=\"video\" class=\"position-relative bg-dark\">\r\n");
      out.write("      <div class=\"container-fluid p-0\">\r\n");
      out.write("        <video autoplay muted loop class=\"custom-video\">\r\n");
      out.write("          <source src=\"images/video.mp4\" type=\"video/mp4\" />\r\n");
      out.write("          Your browser does not support the video tag.\r\n");
      out.write("        </video>\r\n");
      out.write("        <!-- Hero Overlay -->\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center\"\r\n");
      out.write("          style=\"\r\n");
      out.write("            background: linear-gradient(\r\n");
      out.write("              to right,\r\n");
      out.write("              rgba(0, 0, 0, 0.4) 0%,\r\n");
      out.write("              rgba(0, 0, 0, 0.1) 60%,\r\n");
      out.write("              transparent 100%\r\n");
      out.write("            );\r\n");
      out.write("          \"\r\n");
      out.write("        >\r\n");
      out.write("          <div class=\"text-white hero-content text-center\">\r\n");
      out.write("            <h1\r\n");
      out.write("              class=\"hero-heading fw-bold mb-3\"\r\n");
      out.write("              style=\"\r\n");
      out.write("                letter-spacing: 2px;\r\n");
      out.write("                text-shadow: 0 3px 15px rgba(0, 0, 0, 0.5);\r\n");
      out.write("              \"\r\n");
      out.write("            >\r\n");
      out.write("              Wear Your Confidence\r\n");
      out.write("            </h1>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"hero-tagline mb-0\"\r\n");
      out.write("              style=\"\r\n");
      out.write("                opacity: 0.92;\r\n");
      out.write("                line-height: 1.7;\r\n");
      out.write("                text-shadow: 0 1px 6px rgba(0, 0, 0, 0.45);\r\n");
      out.write("              \"\r\n");
      out.write("            >\r\n");
      out.write("              Own the room. Wear it bold, wear it soft.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Summer Trends Section -->\r\n");
      out.write("    <section\r\n");
      out.write("      id=\"summerSection\"\r\n");
      out.write("      class=\"position-relative w-100\"\r\n");
      out.write("      style=\"overflow: hidden\"\r\n");
      out.write("    >\r\n");
      out.write("      <!-- Three images side by side, horizontally scrollable -->\r\n");
      out.write("      <div class=\"d-flex flex-nowrap overflow-x-auto summer-img-row\">\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"images/summer-product1.png\"\r\n");
      out.write("          class=\"summer-img flex-shrink-0\"\r\n");
      out.write("          alt=\"Summer 1\"\r\n");
      out.write("        />\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"images/summer-product2.png\"\r\n");
      out.write("          class=\"summer-img flex-shrink-0\"\r\n");
      out.write("          alt=\"Summer 2\"\r\n");
      out.write("        />\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"images/summer-product3.png\"\r\n");
      out.write("          class=\"summer-img flex-shrink-0\"\r\n");
      out.write("          alt=\"Summer 3\"\r\n");
      out.write("        />\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Overlay text and button -->\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"position-absolute top-0 start-0 w-100 h-100 d-flex flex-column justify-content-center align-items-center text-center\"\r\n");
      out.write("        style=\"background: rgba(0, 0, 0, 0.3); pointer-events: none\"\r\n");
      out.write("      >\r\n");
      out.write("        <h2\r\n");
      out.write("          class=\"text-white fw-bold mb-3\"\r\n");
      out.write("          style=\"\r\n");
      out.write("            pointer-events: auto;\r\n");
      out.write("            font-size: clamp(1.2rem, 3vw, 2.2rem);\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("          \"\r\n");
      out.write("        >\r\n");
      out.write("          Upcoming Summer Trends\r\n");
      out.write("        </h2>\r\n");
      out.write("        <a\r\n");
      out.write("          href=\"summer.html\"\r\n");
      out.write("          class=\"btn btn-light px-4 py-2 fw-semibold\"\r\n");
      out.write("          style=\"border-radius: 30px; pointer-events: auto\"\r\n");
      out.write("        >\r\n");
      out.write("          Explore &nbsp;&rarr;\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Featured Products Section -->\r\n");
      out.write("    <section id=\"products\" class=\"container-fluid px-5 py-5\">\r\n");
      out.write("      <div class=\"row mb-4\">\r\n");
      out.write("        <div class=\"col-12 text-center\">\r\n");
      out.write("          <h2 class=\"section-heading\">Featured Products</h2>\r\n");
      out.write("          <p class=\"section-sub\">Handpicked favorites just for you</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Scroll wrapper: left/right arrows on mobile -->\r\n");
      out.write("      <div class=\"scroll-wrapper\">\r\n");
      out.write("        <button\r\n");
      out.write("          class=\"scroll-arrow left\"\r\n");
      out.write("          onclick=\"\r\n");
      out.write("            document\r\n");
      out.write("              .getElementById('productScroll')\r\n");
      out.write("              .scrollBy({ left: -220, behavior: 'smooth' })\r\n");
      out.write("          \"\r\n");
      out.write("        >\r\n");
      out.write("          &laquo;\r\n");
      out.write("        </button>\r\n");
      out.write("        <button\r\n");
      out.write("          class=\"scroll-arrow right\"\r\n");
      out.write("          onclick=\"\r\n");
      out.write("            document\r\n");
      out.write("              .getElementById('productScroll')\r\n");
      out.write("              .scrollBy({ left: 220, behavior: 'smooth' })\r\n");
      out.write("          \"\r\n");
      out.write("        >\r\n");
      out.write("          &raquo;\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <!-- Horizontal Scroll Container -->\r\n");
      out.write("        <div\r\n");
      out.write("          id=\"productScroll\"\r\n");
      out.write("          class=\"row flex-nowrap overflow-auto pb-4 g-4 justify-content-lg-center\"\r\n");
      out.write("          style=\"scroll-behavior: smooth\"\r\n");
      out.write("        >\r\n");
      out.write("          <!-- Product 1 -->\r\n");
      out.write("          <div class=\"col-10 col-md-4 col-lg-2 flex-shrink-0\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm product-card\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"images/product1.png\"\r\n");
      out.write("                class=\"card-img-top\"\r\n");
      out.write("                alt=\"Product 1\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"card-body text-center\">\r\n");
      out.write("                <h5 class=\"card-title\">Off Shoulder Tee</h5>\r\n");
      out.write("                <p class=\"card-text text-muted\">NPR 2500</p>\r\n");
      out.write("                <a\r\n");
      out.write("                  href=\"product1.html\"\r\n");
      out.write("                  class=\"btn btn-primary btn-sm stretched-link\"\r\n");
      out.write("                  >View Details</a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Product 2 -->\r\n");
      out.write("          <div class=\"col-10 col-md-4 col-lg-2 flex-shrink-0\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm product-card\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"images/product2.png\"\r\n");
      out.write("                class=\"card-img-top\"\r\n");
      out.write("                alt=\"Product 2\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"card-body text-center\">\r\n");
      out.write("                <h5 class=\"card-title\">Crop Tee</h5>\r\n");
      out.write("                <p class=\"card-text text-muted\">NPR 1800</p>\r\n");
      out.write("                <a\r\n");
      out.write("                  href=\"product2.html\"\r\n");
      out.write("                  class=\"btn btn-primary btn-sm stretched-link\"\r\n");
      out.write("                  >View Details</a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Product 3 -->\r\n");
      out.write("          <div class=\"col-10 col-md-4 col-lg-2 flex-shrink-0\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm product-card\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"images/product3.png\"\r\n");
      out.write("                class=\"card-img-top\"\r\n");
      out.write("                alt=\"Product 3\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"card-body text-center\">\r\n");
      out.write("                <h5 class=\"card-title\">Basic Tee</h5>\r\n");
      out.write("                <p class=\"card-text text-muted\">NPR 1200</p>\r\n");
      out.write("                <a\r\n");
      out.write("                  href=\"product3.html\"\r\n");
      out.write("                  class=\"btn btn-primary btn-sm stretched-link\"\r\n");
      out.write("                  >View Details</a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Product 4 -->\r\n");
      out.write("          <div class=\"col-10 col-md-4 col-lg-2 flex-shrink-0\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm product-card\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"images/product4.png\"\r\n");
      out.write("                class=\"card-img-top\"\r\n");
      out.write("                alt=\"Product 4\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"card-body text-center\">\r\n");
      out.write("                <h5 class=\"card-title\">Floral Sleeveless Dress</h5>\r\n");
      out.write("                <p class=\"card-text text-muted\">NPR 3500</p>\r\n");
      out.write("                <a\r\n");
      out.write("                  href=\"product4.html\"\r\n");
      out.write("                  class=\"btn btn-primary btn-sm stretched-link\"\r\n");
      out.write("                  >View Details</a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Product 5 -->\r\n");
      out.write("          <div class=\"col-10 col-md-4 col-lg-2 flex-shrink-0\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm product-card\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"images/product5.png\"\r\n");
      out.write("                class=\"card-img-top\"\r\n");
      out.write("                alt=\"Product 5\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"card-body text-center\">\r\n");
      out.write("                <h5 class=\"card-title\">Summer Dress</h5>\r\n");
      out.write("                <p class=\"card-text text-muted\">NPR 2800</p>\r\n");
      out.write("                <a\r\n");
      out.write("                  href=\"product5.html\"\r\n");
      out.write("                  class=\"btn btn-primary btn-sm stretched-link\"\r\n");
      out.write("                  >View Details</a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Product 6 -->\r\n");
      out.write("          <div class=\"col-10 col-md-4 col-lg-2 flex-shrink-0\">\r\n");
      out.write("            <div class=\"card h-100 border-0 shadow-sm product-card\">\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"images/product6.png\"\r\n");
      out.write("                class=\"card-img-top\"\r\n");
      out.write("                alt=\"Product 6\"\r\n");
      out.write("              />\r\n");
      out.write("              <div class=\"card-body text-center\">\r\n");
      out.write("                <h5 class=\"card-title\">Silk Dress</h5>\r\n");
      out.write("                <p class=\"card-text text-muted\">NPR 3000</p>\r\n");
      out.write("                <a\r\n");
      out.write("                  href=\"product6.html\"\r\n");
      out.write("                  class=\"btn btn-primary btn-sm stretched-link\"\r\n");
      out.write("                  >View Details</a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /scroll-wrapper -->\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Pagination -->\r\n");
      out.write("    <div class=\"container text-center my-4\">\r\n");
      out.write("      <nav aria-label=\"Page navigation example\">\r\n");
      out.write("        <ul class=\"pagination justify-content-center\">\r\n");
      out.write("          <li class=\"page-item disabled\">\r\n");
      out.write("            <a class=\"page-link\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\"\r\n");
      out.write("              >&laquo;</a\r\n");
      out.write("            >\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"page-item\">\r\n");
      out.write("            <a class=\"page-link\" href=\"page1.html\">1</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"page-item\">\r\n");
      out.write("            <a class=\"page-link\" href=\"page2.html\">2</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"page-item\">\r\n");
      out.write("            <a class=\"page-link\" href=\"page3.html\">3</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"page-item\">\r\n");
      out.write("            <a class=\"page-link\" href=\"page4.html\">4</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"page-item\">\r\n");
      out.write("            <a class=\"page-link\" href=\"page2.html\">&raquo;</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"ashh-footer text-white pt-5 pb-4\">\r\n");
      out.write("      <div class=\"container text-center text-md-start\">\r\n");
      out.write("        <div class=\"row text-center text-md-start\">\r\n");
      out.write("          <div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("            <h5 class=\"text-uppercase mb-4 fw-bold text-warning\">\r\n");
      out.write("              ASHH Clothing\r\n");
      out.write("            </h5>\r\n");
      out.write("            <p>\r\n");
      out.write("              Your one-stop destination for premium fashion. We bring you the\r\n");
      out.write("              latest trends at affordable prices.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("            <h5 class=\"text-uppercase mb-4 fw-bold text-warning\">Links</h5>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"about.html\" class=\"text-white text-decoration-none\"\r\n");
      out.write("                >About Us</a\r\n");
      out.write("              >\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"contact.html\" class=\"text-white text-decoration-none\"\r\n");
      out.write("                >Contact Us</a\r\n");
      out.write("              >\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("            <h5 class=\"text-uppercase mb-4 fw-bold text-warning\">Contact Us</h5>\r\n");
      out.write("            <p><i class=\"fas fa-home mr-3\"></i> Kathmandu, Nepal</p>\r\n");
      out.write("            <p><i class=\"fas fa-envelope mr-3\"></i> contact@ashh.com</p>\r\n");
      out.write("            <p><i class=\"fas fa-phone mr-3\"></i> +977 9800000000</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr class=\"mb-4\" />\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-md-7 col-lg-8\">\r\n");
      out.write("            <p>\r\n");
      out.write("              Copyright ÃÂ© 2026 All rights reserved by:\r\n");
      out.write("              <a href=\"#\" class=\"text-warning text-decoration-none\"\r\n");
      out.write("                ><strong>ASHH Clothing</strong></a\r\n");
      out.write("              >\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5 col-lg-4\">\r\n");
      out.write("            <div class=\"text-center text-md-end\">\r\n");
      out.write("              <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("                <li class=\"list-inline-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"btn-floating btn-sm text-white\"\r\n");
      out.write("                    ><i class=\"fab fa-facebook\"></i\r\n");
      out.write("                  ></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"list-inline-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"btn-floating btn-sm text-white\"\r\n");
      out.write("                    ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("                  ></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"list-inline-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"btn-floating btn-sm text-white\"\r\n");
      out.write("                    ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("                  ></a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
