package com.example.model;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * User Model — represents a registered user on the ASHH Clothing website.
 *
 * Fields:
 *  - firstName, lastName : the user's full name
 *  - email               : must be a valid email, used as the unique login
 *  - password            : stored in plain-text here for simplicity (in production, always hash it!)
 *  - phone               : optional 10-digit contact number
 *
 * Validation annotations are checked by @Valid in the Controller.
 */
public class User {

    private Long id;  // Auto-generated by the database

    @NotBlank(message = "First name is required")
    private String firstName;

    @NotBlank(message = "Last name is required")
    private String lastName;

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid email address")
    private String email;

    @NotBlank(message = "Password is required")
    @Size(min = 6, message = "Password must be at least 6 characters")
    private String password;

    @Pattern(regexp = "^(\\d{10})?$", message = "Phone number must be exactly 10 digits (or leave blank)")
    private String phone;

    // No-argument constructor — required by Jackson to convert JSON into this object
    public User() {
    }

    // Constructor with all fields (except id, which is auto-generated)
    public User(String firstName, String lastName, String email, String password, String phone) {
        this.firstName = firstName;
        this.lastName  = lastName;
        this.email     = email;
        this.password  = password;
        this.phone     = phone;
    }

    // Getters and Setters

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }
}